### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by ghost** [jblas-project/jblas#83]
java.lang.UnsatisfiedLinkError: No implementation found for void org.jblas.NativeBlas.sgemm(char, char, int, int, int, float, float[], int, int, float[], int, int, float, float[], int, int) (tried Java_org_jblas_NativeBlas_sgemm and Java_org_jblas_NativeBlas_sgemm__CCIIIF_3FII_3FIIF_3FII)

i compiled jblas in android and got this error on mmul operation.
How to fix this error?

**Comment by mikiobraun** [comment]
Hey ghost, four years later, sorry for the late answer...

jblas depends on native libraries, unless you link against an Android version of BLAS and LAPACK, it probably won't work.

I recently did a release to 1.2.5 which now uses openblas, and that seems to compile for Android, so you could give that a try. https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android.

Closing the issue now (mostly because it is so old), feel free to reopen if it still matters.
